spring.application.name=ansik

server.port=8088

# ========================================================
# Database Configuration
# ========================================================

spring.datasource.url=jdbc:mysql://localhost:3306/ansik_db
spring.datasource.username=root
spring.datasource.password=19g61t61r!

# ========================================================
# JPA Configuration
# ========================================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ========================================================
# API Keys
# ========================================================

api.kakao.key=KakaoAK ea731a9e930f5151c7ccc30d50d0996e

api.naver.client-id=fibxb4zdoc

api.naver.client-secret=0cNuSzrIWvE1z4xhFGQUF171JEDDN7IT1fLdjTnz

api.tourapi.key=ecb776bfdd4b1760b36175140757e31841453b0c1aa8c5ac261dcf182a6ab4bf